### ISSUE TITLE
After the end of a track, the same track is repeated (random mode in gmusic library)

### ISSUE THREAD

**Issue by M0Rf30** [mopidy/mopidy-gmusic#165] opened 2017-01-14 21:43 UTC
Hi,
I've configured a mopidy instance with gmusic plugin. I use MusicBox web interface
everything seems to be fine, but here what happens:
* Go to gmusic library -> tracks
* Select a track to play
* Put random mode
* The selected song is played
* Another different one after
* It repeats the last one 

Could I help in any way?

**Comment by kingosticks** [comment] 2017-01-14 21:44
Is this actually specific to gmusic or is that the only backend you have
tried?

**Comment by M0Rf30** [comment] 2017-01-14 21:49
Is the only backend that I'm using. I'll try another one and reply

**Comment by M0Rf30** [comment] 2017-01-15 00:29
I can only try gmusic backed, cause I've no spotify premium, dirble is for radios and not single tracks and no local files available

**Comment by sashaverona** [comment] 2018-01-17 18:55
Very late, but I can confirm that Spotify/local backends function normally. Random mode need not be enabled. To actually change tracks, "next track" must be sent twice in rapid succession.

I believe that [#182](https://github.com/mopidy/mopidy-gmusic/issues/182), [#183](https://github.com/mopidy/mopidy-gmusic/issues/183) are essentially duplicate issues, or at least similar manifestations of the same bug.

The outputs of `mopidy config` and `mopidy deps` are attached, as are debug logs for both GMusic and Spotify backends. Each log depicts startup; searching and selecting an album; sending "next track" once; sending "next track" twice rapidly, as above; and teardown.

[config.txt](https://github.com/mopidy/mopidy-gmusic/files/1640246/config.txt)
[deps.txt](https://github.com/mopidy/mopidy-gmusic/files/1640245/deps.txt)
[gmusic.log](https://github.com/mopidy/mopidy-gmusic/files/1640243/gmusic.log)
[spotify.log](https://github.com/mopidy/mopidy-gmusic/files/1640244/spotify.log)

Please let me know if I can provide more information.

**Comment by jodal** [comment] 2020-12-06 23:35
Closing because Google Play Music has been shut down, and this project is being discontinued.

**Closed by jodal** 2020-12-06 23:35 UTC
