### ISSUE TITLE
Artists and albums are listed multiple times

### ISSUE THREAD

**Issue by makrLL** [mopidy/mopidy-gmusic#206] opened 2018-11-07 18:58 UTC
I just started uploading part of my local library to Google music. Using ncmpcpp and it seems that almost all artists are listed twice, and albums are listed multiple times, but the entries _behave_ differently: [Artist] [2]] lists all the tracks while [Artist] lists albums, of which multiple versions are then listed too (pictures below). Contents of albums seems to be the same, and they all seem to work the same.
![1](https://user-images.githubusercontent.com/44705361/48153504-abe34380-e2c6-11e8-95aa-b685aec80ac6.png)
![2](https://user-images.githubusercontent.com/44705361/48153508-b1d92480-e2c6-11e8-8253-2a80b811cfa4.png)
![3](https://user-images.githubusercontent.com/44705361/48153511-b30a5180-e2c6-11e8-8e81-80e2fa9509fe.png)

(Also can't see the library in "Media library" section of ncmpcpp bot only in browse tab, but that seems to be a pending issue still)

All Access is disabled and this is my simple config: 
```
[gmusic]
username = <user>
password = ****
deviceid = <id>
all_access = false
bitrate = 320
```

**Comment by jjok** [comment] 2018-11-07 21:51
Duplicate of #139?

**Closed** 2020-03-10 23:40 UTC
