### ISSUE TITLE
pykka: Unhandled exception in GMusicBackend 

### ISSUE THREAD

**Issue by ernesst** [mopidy/mopidy-gmusic#107] opened 2016-02-27 22:22 UTC
All, 
First of al thanks for all the great job achieved !

I'm encountering an issue after updating python package and my raspbian system. 

```
2016-02-27 21:56:56,552 INFO [5030:MainThread] gmusicapi.Mobileclient1: !-- begin debug log --!
2016-02-27 21:56:56,555 INFO [5030:MainThread] gmusicapi.Mobileclient1: version: 7.0.1-dev
2016-02-27 21:56:56,557 INFO [5030:MainThread] gmusicapi.Mobileclient1: logging to: /var/lib/mopidy/.cache/gmusicapi/log/gmusicapi.log
2016-02-27 21:56:56,559 INFO [5030:MainThread] gmusicapi.Mobileclient1: initialized
2016-02-27 21:56:56,563 INFO [5030:MainThread] gmusicapi.Mobileclient1: logged out
2016-02-27 21:56:56,564 INFO [5030:Audio-2] mopidy.audio.actor: Audio output set to "autoaudiosink"
2016-02-27 21:56:56,648 INFO [5030:GMusicBackend-6] requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): android.clients.google.com
2016-02-27 21:56:56,809 ERROR [5030:GMusicBackend-6] pykka: Unhandled exception in GMusicBackend (urn:uuid:c7f0f19e-164b-4c87-9677-699c02ac7515):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 192, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/actor.py", line 51, in on_start
    self.config['gmusic']['deviceid'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 60, in login
    authenticated = self.api.login(username, password, device_id)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 63, in login
    if not self.session.login(email, password, android_id):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 171, in login
    res = gpsoauth.perform_master_login(email, password, android_id)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 66, in perform_master_login
    return _perform_auth_request(data)
  File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
    headers={'User-Agent': useragent})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
2016-02-27 21:56:56,936 ERROR [5030:MainThread] mopidy.commands: Actor died: GMusicBackend (urn:uuid:c7f0f19e-164b-4c87-9677-699c02ac7515) stopped before handling the message
```

about my config 

```
pip list
appdirs (1.4.0)
backports-abc (0.4)
backports.ssl-match-hostname (3.5.0.1)
beautifulsoup4 (4.4.1)
cachetools (1.1.5)
certifi (2015.11.20.1)
cffi (1.5.2)
chardet (2.3.0)
colorama (0.3.6)
cryptography (1.2.2)
decorator (4.0.9)
enum34 (1.1.2)
funcsigs (0.4)
fuse-python (0.2.1)
fusepy (2.0.2)
future (0.15.2)
gmusicapi (7.0.1.dev0)
gpsoauth (0.0.5)
html5lib (0.9999999)
httplib2 (0.9.2)
idna (2.0)
ipaddress (1.0.16)
MechanicalSoup (0.4.0)
mock (1.3.0)
Mopidy (2.0.0)
Mopidy-GMusic (1.0.0)
Mopidy-Mobile (1.6.9)
Mopidy-MusicBox-Webclient (2.1.1)
Mopidy-Podcast (1.1.2)
Mopidy-Podcast-gpodder.net (1.0.0)
mutagen (1.31)
MySQL-python (1.2.3)
ndg-httpsclient (0.4.0)
oauth2client (2.0.0.post1)
pbr (1.8.1)
pip (8.0.3)
proboscis (1.2.6.0)
protobuf (2.6.1)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
pycrypto (2.6.1)
pycryptodome (3.4)
pycurl (7.19.5)
pygobject (3.14.0)
Pykka (1.2.1)
pyOpenSSL (0.15.1)
python-dateutil (2.4.2)
requests (2.7.0)
RPi.GPIO (0.6.1)
rsa (3.3)
setuptools (20.2.2)
singledispatch (3.4.0.3)
six (1.10.0)
tornado (4.3)
uritools (1.0.1)
urllib3 (1.9.1)
validictory (1.0.1)
wheel (0.29.0)

```

Mopidy deps

```
mopidy deps
Executable: /usr/bin/mopidy
Platform: Linux-4.1.17-v7+-armv7l-with-debian-8.0
Python: CPython 2.7.9 from /usr/lib/python2.7
Mopidy: 2.0.0 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
  tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
    backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
    singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
      six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
    backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
Mopidy-MusicBox-Webclient: 2.1.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1.0: 2.0.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
    requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
      backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
Mopidy-GMusic: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 2.0.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
    requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
      backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  gmusicapi>=6.0: 7.0.1.dev0 from /usr/local/lib/python2.7/dist-packages
    validictory!=0.9.2,>=0.8.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
    decorator>=3.3.1: 4.0.9 from /usr/local/lib/python2.7/dist-packages
    mutagen>=1.18: 1.31 from /usr/local/lib/python2.7/dist-packages
    protobuf>=2.4.1: 2.6.1 from /usr/local/lib/python2.7/dist-packages
      setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
    requests!=1.2.0,!=2.2.1,<2.8.0,>=1.1.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    python-dateutil!=2.0,>=1.3: 2.4.2 from /usr/local/lib/python2.7/dist-packages
      six>=1.5: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/local/lib/python2.7/dist-packages
    oauth2client>=1.1: 2.0.0.post1 from /usr/local/lib/python2.7/dist-packages
      six>=1.6.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      pyasn1-modules>=0.0.5: 0.0.8 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
      rsa>=3.1.4: 3.3 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.3: 0.1.9 from /usr/local/lib/python2.7/dist-packages
      pyasn1>=0.1.7: 0.1.9 from /usr/local/lib/python2.7/dist-packages
      httplib2>=0.9.1: 0.9.2 from /usr/local/lib/python2.7/dist-packages
    mock>=0.7.0: 1.3.0 from /usr/local/lib/python2.7/dist-packages
      funcsigs: 0.4 from /usr/local/lib/python2.7/dist-packages
      pbr>=0.11: 1.8.1 from /usr/local/lib/python2.7/dist-packages
      six>=1.7: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    appdirs>=1.1.0: 1.4.0 from /usr/local/lib/python2.7/dist-packages
    gpsoauth==0.0.5: 0.0.5 from /usr/local/lib/python2.7/dist-packages
      pycrypto>=2.5: 2.6.1 from /usr/lib/python2.7/dist-packages
      pyopenssl: 0.15.1 from /usr/local/lib/python2.7/dist-packages
        six>=1.5.2: 1.10.0 from /usr/local/lib/python2.7/dist-packages
        cryptography>=0.7: 1.2.2 from /usr/local/lib/python2.7/dist-packages
          enum34: 1.1.2 from /usr/local/lib/python2.7/dist-packages
          ipaddress: 1.0.16 from /usr/local/lib/python2.7/dist-packages
          pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
          six>=1.4.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
          setuptools>=1.0: 20.2.2 from /usr/local/lib/python2.7/dist-packages
          idna>=2.0: 2.0 from /usr/local/lib/python2.7/dist-packages
          cffi>=1.4.1: 1.5.2 from /usr/local/lib/python2.7/dist-packages
            pycparser: 2.14 from /usr/local/lib/python2.7/dist-packages
      requests: 2.7.0 from /usr/local/lib/python2.7/dist-packages
      ndg-httpsclient: 0.4.0 from /usr/local/lib/python2.7/dist-packages
        PyOpenSSL: 0.15.1 from /usr/local/lib/python2.7/dist-packages
          six>=1.5.2: 1.10.0 from /usr/local/lib/python2.7/dist-packages
          cryptography>=0.7: 1.2.2 from /usr/local/lib/python2.7/dist-packages
            enum34: 1.1.2 from /usr/local/lib/python2.7/dist-packages
            ipaddress: 1.0.16 from /usr/local/lib/python2.7/dist-packages
            pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
            six>=1.4.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
            setuptools>=1.0: 20.2.2 from /usr/local/lib/python2.7/dist-packages
            idna>=2.0: 2.0 from /usr/local/lib/python2.7/dist-packages
            cffi>=1.4.1: 1.5.2 from /usr/local/lib/python2.7/dist-packages
              pycparser: 2.14 from /usr/local/lib/python2.7/dist-packages
      pyasn1: 0.1.9 from /usr/local/lib/python2.7/dist-packages
    MechanicalSoup: 0.4.0 from /usr/local/lib/python2.7/dist-packages
      requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
      beautifulsoup4: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      six>=1.4: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    pyopenssl: 0.15.1 from /usr/local/lib/python2.7/dist-packages
      six>=1.5.2: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      cryptography>=0.7: 1.2.2 from /usr/local/lib/python2.7/dist-packages
        enum34: 1.1.2 from /usr/local/lib/python2.7/dist-packages
        ipaddress: 1.0.16 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
        six>=1.4.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
        setuptools>=1.0: 20.2.2 from /usr/local/lib/python2.7/dist-packages
        idna>=2.0: 2.0 from /usr/local/lib/python2.7/dist-packages
        cffi>=1.4.1: 1.5.2 from /usr/local/lib/python2.7/dist-packages
          pycparser: 2.14 from /usr/local/lib/python2.7/dist-packages
    ndg-httpsclient: 0.4.0 from /usr/local/lib/python2.7/dist-packages
      PyOpenSSL: 0.15.1 from /usr/local/lib/python2.7/dist-packages
        six>=1.5.2: 1.10.0 from /usr/local/lib/python2.7/dist-packages
        cryptography>=0.7: 1.2.2 from /usr/local/lib/python2.7/dist-packages
          enum34: 1.1.2 from /usr/local/lib/python2.7/dist-packages
          ipaddress: 1.0.16 from /usr/local/lib/python2.7/dist-packages
          pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
          six>=1.4.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
          setuptools>=1.0: 20.2.2 from /usr/local/lib/python2.7/dist-packages
          idna>=2.0: 2.0 from /usr/local/lib/python2.7/dist-packages
          cffi>=1.4.1: 1.5.2 from /usr/local/lib/python2.7/dist-packages
            pycparser: 2.14 from /usr/local/lib/python2.7/dist-packages
    pyasn1: 0.1.9 from /usr/local/lib/python2.7/dist-packages
Mopidy-Mobile: 1.6.9 from /usr/local/lib/python2.7/dist-packages
  setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 2.0.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
    requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
      backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
Mopidy-Podcast-gpodder.net: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 2.0.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
    requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
      backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  Mopidy-Podcast>=1.0.0: 1.1.2 from /usr/local/lib/python2.7/dist-packages
    setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
    uritools>=0.8.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
      ipaddress>=1.0.6: 1.0.16 from /usr/local/lib/python2.7/dist-packages
    Mopidy>=0.19: 2.0.0 from /usr/lib/python2.7/dist-packages
      Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
      requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
      tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
        backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
        singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
          six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
        certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
        backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
    cachetools>=0.7.0: 1.1.5 from /usr/local/lib/python2.7/dist-packages
    Pykka>=1.1.0: 1.2.1 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-Podcast: 1.1.2 from /usr/local/lib/python2.7/dist-packages
  setuptools: 20.2.2 from /usr/local/lib/python2.7/dist-packages
  uritools>=0.8.0: 1.0.1 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6: 1.0.16 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.19: 2.0.0 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/local/lib/python2.7/dist-packages
    requests>=2.0: 2.7.0 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.3 from /usr/local/lib/python2.7/dist-packages
      backports.ssl-match-hostname: 3.5.0.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2015.11.20.1 from /usr/local/lib/python2.7/dist-packages
      backports-abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  cachetools>=0.7.0: 1.1.5 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1.0: 1.2.1 from /usr/local/lib/python2.7/dist-packages
GStreamer: 1.4.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.14.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mpg123audiodec

```

Mopidy.conf

```
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
data_dir = /var/lib/mopidy/local
media_dir = /var/lib/mopidy/media

# For further information about options in this file see:
#   http://docs.mopidy.com/
#
# The initial commented out values reflect the defaults as of:
#   Mopidy 1.1.1
#   Mopidy-ALSAMixer 1.0.3
#   Mopidy-File 1.1.1
#   Mopidy-HTTP 1.1.1
#   Mopidy-Local 1.1.1
#   Mopidy-M3U 1.1.1
#   Mopidy-MPD 1.1.1
#   Mopidy-Podcast 1.1.2
#   Mopidy-SoftwareMixer 1.1.1
#   Mopidy-Stream 1.1.1
#
# Available options and defaults might have changed since then,
# run `mopidy config` to see the current effective config and
# `mopidy --version` to check the current version.
[audio]
mixer_volume = 55


[podcast]
enabled = true
browse_limit = 100
search_limit = 20
search_details = on
update_interval = 86400
feeds = 
        http://cdn1-europe1.new2.ladmedia.fr/var/exports/podcasts/sound/au-coeur-de-l-histoire.xml 
        http://www.deejay.it/la_bomba.xml
feeds_root_name = Subscribed Feeds
feeds_cache_size = 32
feeds_cache_ttl = 3600
feeds_timeout = 10

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
password = bounty
max_connections = 20
connection_timeout = 60
#zeroconf = Mopidy MPD server on $hostname
#command_blacklist = 
#  listall
#  listallinfo

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
#static_dir =
zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
#metadata_blacklist = 
#timeout = 5000

[m3u]
enabled = true
playlists_dir =

[softwaremixer]
enabled = true

[file]
enabled = false

[local]
enabled = false
[mpris]
enabled = true

[gmusic]
username = YYYYYY
password = XXXXXXX
all_access = true
# Show radio stations in content browser
radio_stations_in_browse = true
# Show radio stations as playlists
radio_stations_as_playlists = false
# Limit the number of radio stations, unlimited if unset
radio_stations_count =
# Limit the number or tracks for each radio station
radio_tracks_count = 50
#deviceid = FFFFFFFFFFf1


[podcast-gpodder]
enabled = false
# gpodder.net base URL
base_url = http://gpodder.net/
# user-friendly name for browsing the gpodder.net root directory
root_name = Podcast
# format string for tag (top-level) results; field names are: tag,
# usage
tag_format = {tag}
# format string for podcast results; field names are: description,
# subscribers, subscribers_last_week, title, url, website
podcast_format = {title}
# default number of tags or podcasts to show when browsing
count = 20
# HTTP request timeout in seconds
timeout = 10



```

**Comment by ernesst** [comment] 2016-02-29 19:38
I found a trick,

I've removed mopidy and requests ded package and i've installed them via PIP.
To fix the SSl issue : export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt 

To start mopidy with the system in /etc/rc.local i've added
`export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt && /usr/bin/mopidy --config /etc/mopidy/mopidy.conf`

**Comment by 5AMsan** [comment] 2016-05-04 06:45
I didn't manage to use your trick @ernesst . How do I set the envvar for a non-shell user ? My mopidy install uses user mopidy with no shell nor home.
Allready done that :
`cat /etc/environment
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt`

**Comment by barnacletoast** [comment] 2016-05-04 17:43
If you're using systemd, try adding it under the Service (for ex in /lib/systemd/system/mopidy.service) like so:
```
[Service]
Environment=REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
User=mopidy
ExecStart=/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf
```

Then systemctl  daemon-reload and try restarting mopidy.

**Comment by 5AMsan** [comment] 2016-05-09 07:27
Great, some things are back but Google Music still has some severe issues : no track found when browsing, no allAccess search, ...

**Comment by belak** [comment] 2016-07-14 08:12
It sounds like this bug is due to a specific distro/setup of mopidy-gmusic, since requests should be able to find the ca-certificates automatically. Can you give me any more information about your setup, things that might be out of the ordinary?

**Comment by rhyst** [comment] 2016-09-21 23:02
I think I'm getting a similar error on raspberry pi 3 running Raspbian:

Debug log
[mopidy.log](https://github.com/mopidy/mopidy-gmusic/files/486183/mopidy.txt)

Mopidy deps
[mopidydeps.txt](https://github.com/mopidy/mopidy-gmusic/files/486194/mopidydeps.txt)

Mopidy conf
[mopidy.conf.txt](https://github.com/mopidy/mopidy-gmusic/files/486193/mopidy.conf.txt)

**Comment by belak** [comment] 2016-09-21 23:14
Hi @rhyst, that looks like it's probably related to #143. I plan on getting a fix out as soon as gmusicapi releases a stable version (it's already in their develop branch) with the relevant fixes.

**Comment by rhyst** [comment] 2016-09-21 23:22
Thanks for the quick response! In the mean time is there any work around?

**Comment by belak** [comment] 2016-09-21 23:29
Yes, however it involves installing both mopidy-gmusic and gmusicapi from git.

**Comment by rhyst** [comment] 2016-09-21 23:35
Just to check, I am also getting some sort of connection error in addition to the m3u error.

ConnectionError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x72f752b0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Is that related? Connecting worked when I just had mopidy-gmusic v1 (but obviously all access didn't work).

**Comment by ernesst** [comment] 2016-09-22 03:23
Gents, It's a issue with a package in Raspbian, I think requests.
To fix it, I removed mopidy deb packages and other then install with pip package.

**Comment by rhyst** [comment] 2016-09-22 17:04
Just FYI I fixed my issue by updating to the very latest gmusicapi (installed from github). So I have Mopidy 2.0.1, Mopidy GMusic 2.0.0rc1, and gmusicapi 10.0.2rc1.

**Comment by belak** [comment] 2016-10-31 07:07
I'm marking this as fixed because it should be better on develop so I can track this for the next release.

**Closed by belak** 2016-10-31 07:07 UTC
Labels: bug
