### ISSUE TITLE
Ordering of search results

### ISSUE THREAD

**Issue by fredludlow** [mopidy/mopidy-gmusic#108] opened 2016-03-06 12:38 UTC
Hi,
Firstly, big thanks to the mopidy and mopidy-gmusic authors and maintainers. Was very pleased how easy it was to build a raspberry pi streamer for my hifi that plays Google All Access songs. One small issue (which I think I can fix but wanted some input from others before doing so):

Search results in gmusic are currently unordered. Internally the library module searches two sources, the gmusic "library" tracks and all access tracks (if enabled). I'm not sure how you'd apply a sensible ordering to library tracks, other than that they possibly should come before all-access tracks?

All Access tracks are retrieved through the gmusicapi search_all_access function, which does return ordered lists of tracks, artists, albums. However, these get merged with the library results via a python set so any ordering is lost. If you search for a band name that's also a fairly common word (e.g. "Pulp") the order of results is just the arbitrary order that you get when iterating over a set, while the actual results that gmusicapi is returning are in a much more intelligent order (it's like Google have had some practice with this whole search thing ;) ). 

It's a fairly small change to preserve the ordering of all access results and I'm happy to send a pull request, but first wanted to check. 

1) Should "my library" results come before all access, or after? 

2) Is this whole thing pointless because the order gets mangled further up the mopidy stack?

3) Am I missing some neat functionality in the main mopidy package that would solve this better?

Cheers,

Fred

**Comment by belak** [comment] 2016-07-02 22:20
1. I'm not sure that's very well defined, but it would be interesting to see how people 'expect' this to act... even just looking at how the web ui does it.

2. Nope, search results (and just about everything else) are returned as a list, so ordering should be preserved.

3. Not that I'm aware of.

Just at a quick glance, the Web UI appears to order library results first, followed by non-library results. I feel like this might be the expected behavior?

**Comment by belak** [comment] 2016-07-14 09:17
One of the other things I remembered about this... search isn't currently good at filtering. Even if you search by (as an example) album artist, there could still be results where the album artist doesn't match at all.

There was work in #112 to clean this up

**Comment by SicariusNoctis** [comment] 2019-08-14 03:05
To add to this, it would be nice if albums were ordered earlier. (Or a config option.)

**Comment by jodal** [comment] 2020-12-06 23:36
Closing because Google Play Music has been shut down, and this project is being discontinued.

**Closed by jodal** 2020-12-06 23:36 UTC
Labels: C-enhancement
