### ISSUE TITLE
requests 2.10.0 too new? 

### ISSUE THREAD

**Issue by parkerlreed** [mopidy/mopidy-gmusic#118] opened 2016-05-18 03:57 UTC
I'm getting this on a fresh install of mopidy and the gmusic plugin.

Arch x86_64
python2-requests 2.10.0-1

````
[parker@x3720 ~]$ mopidy
INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /home/parker/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Disabled extension gmusic: (requests 2.10.0 (/usr/lib/python2.7/site-packages), Requirement.parse('requests!=1.2.0,!=2.2.1,<2.8.0,>=1.1.0'), set(['gmusicapi']))
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local
INFO     Disabled extensions: gmusic
ERROR    Extension stream failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/lib/python2.7/site-packages/mopidy/stream/__init__.py", line 31, in setup
    from .actor import StreamBackend
  File "/usr/lib/python2.7/site-packages/mopidy/stream/actor.py", line 13, in <module>
    from mopidy.internal import http, playlists
  File "/usr/lib/python2.7/site-packages/mopidy/internal/http.py", line 6, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: M3UBackend, FileBackend, LocalBackend
INFO     No local library metadata cache found at /home/parker/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:0.0.0.0]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     Starting GLib mainloop
````

**Comment by jodal** [comment] 2016-05-18 06:07
Duplicate of #113. Fixed by newer version of gmusicapi.

**Closed by jodal** 2016-05-18 06:07 UTC

**Comment by parkerlreed** [comment] 2016-05-18 12:04
Ok I updated that but now I get this. Something's up with my python install but I'm not sure what. I tried reinstalling every system python package but it didn't clear it up. I got the same vague DependencyWarning with letsencrypt. Any idea what this could be?

````
[parker@x3720 ~]$ mopidy
INFO     Starting Mopidy 2.0.0
INFO     Loading config from builtin defaults
INFO     Loading config from /home/parker/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mpd, http, stream, m3u, softwaremixer, file, local, gmusic
INFO     Disabled extensions: none
ERROR    Extension gmusic failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/__init__.py", line 45, in setup
    from .actor import GMusicBackend
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/actor.py", line 17, in <module>
    from .session import GMusicSession
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 6, in <module>
    import gmusicapi
  File "/usr/lib/python2.7/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "/usr/lib/python2.7/site-packages/gmusicapi/clients/webclient.py", line 11, in <module>
    from gmusicapi.protocol import webclient
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/webclient.py", line 22, in <module>
    from gmusicapi.protocol.shared import Call, authtypes
  File "/usr/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 20, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
ERROR    Extension stream failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/lib/python2.7/site-packages/mopidy/stream/__init__.py", line 31, in setup
    from .actor import StreamBackend
  File "/usr/lib/python2.7/site-packages/mopidy/stream/actor.py", line 13, in <module>
    from mopidy.internal import http, playlists
  File "/usr/lib/python2.7/site-packages/mopidy/internal/http.py", line 6, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: M3UBackend, FileBackend, LocalBackend
INFO     No local library metadata cache found at /home/parker/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:0.0.0.0]:6600
INFO     Starting GLib mainloop
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
````

**Comment by parkerlreed** [comment] 2016-05-18 12:07
Found out what was causing it. Two extra folders in requests. https://bugs.archlinux.org/task/49163 Thanks for the reply.
