### ISSUE TITLE
Cancel refresh on shutdown

### ISSUE THREAD

**Issue by jjok** [mopidy/mopidy-gmusic#147] opened 2016-09-10 10:44 UTC
Is it possible to stop the library and playlist refresh when Mopidy is shut down? If I start it up, then shut down straight away, it hangs for 5 minutes or so, while the refresh completes. This makes development difficult.

**Comment by jjok** [comment] 2016-09-10 10:44
Also, why does the refresh take so long? What's it actually doing?

**Comment by belak** [comment] 2016-09-13 18:29
Can you paste the output of `mopidy deps`? There was some major work that went into this for the 2.0 refactor (still a pre-release) which should cut down the refresh to about 5-10 seconds.

**Comment by belak** [comment] 2016-09-13 18:37
Looking at past issues, it seems like you're using develop. I'll look into adding a verbose mode to make the library update print what it's actually doing.

**Comment by belak** [comment] 2016-09-13 23:52
I'm going to guess that this might be related to the other issue you posted. For uploaded tracks that are linked to tracks with a storeId we might lose track of them, which would require us to look them up a second time. I originally tried to fix this by sanitizing everything to the storeId, but I may need to add an additional translation for tracks with both a storeId and regular id.

**Comment by jjok** [comment] 2016-09-14 22:55
Here's `mopidy deps`:

```
Executable: /usr/bin/mopidy
Platform: Linux-4.4.13+-armv6l-with-debian-8.0
Python: CPython 2.7.9 from /usr/lib/python2.7
Mopidy: 2.0.1 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
  tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
    singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
      six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
    backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
Mopidy-MusicBox-Webclient: 2.3.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1.0: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
Mopidy-GMusic: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  gmusicapi>=10.0: 10.0.1 from /usr/local/lib/python2.7/dist-packages
    validictory!=0.9.2,>=0.8.0: 1.0.2 from /usr/local/lib/python2.7/dist-packages
    decorator>=3.3.1: 4.0.10 from /usr/local/lib/python2.7/dist-packages
    mutagen>=1.18: 1.33.2 from /usr/local/lib/python2.7/dist-packages
    requests!=1.2.0,!=2.2.1,!=2.8.0,!=2.8.1,>=1.1.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    python-dateutil!=2.0,>=1.3: 2.5.3 from /usr/local/lib/python2.7/dist-packages
      six>=1.5: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    proboscis>=1.2.5.1: 1.2.6.0 from /usr/local/lib/python2.7/dist-packages
    oauth2client>=1.1: 2.2.0 from /usr/local/lib/python2.7/dist-packages
      httplib2>=0.9.1: 0.9.2 from /usr/local/lib/python2.7/dist-packages
      pyasn1>=0.1.7: 0.1.9 from /usr/local/lib/python2.7/dist-packages
      pyasn1-modules>=0.0.5: 0.0.8 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
      rsa>=3.1.4: 3.4.2 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.3: 0.1.9 from /usr/local/lib/python2.7/dist-packages
      six>=1.6.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    mock>=0.7.0: 2.0.0 from /usr/local/lib/python2.7/dist-packages
      pbr>=0.11: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      funcsigs>=1; python_version < "3.3": 1.0.2 from /usr/local/lib/python2.7/dist-packages
      six>=1.9: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    appdirs>=1.1.0: 1.4.0 from /usr/local/lib/python2.7/dist-packages
    gpsoauth>=0.2.0: 0.3.0 from /usr/local/lib/python2.7/dist-packages
      pycryptodomex>=3.0: 3.4.2 from /usr/local/lib/python2.7/dist-packages
      requests: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    MechanicalSoup>=0.4.0: 0.4.0 from /usr/local/lib/python2.7/dist-packages
      six>=1.4: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
      beautifulsoup4: 4.4.1 from /usr/local/lib/python2.7/dist-packages
    pyopenssl: 16.0.0 from /usr/local/lib/python2.7/dist-packages
      six>=1.5.2: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      cryptography>=1.3: 1.4 from /usr/local/lib/python2.7/dist-packages
        idna>=2.0: 2.1 from /usr/local/lib/python2.7/dist-packages
        pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
        six>=1.4.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
        setuptools>=11.3: 26.1.1 from /usr/local/lib/python2.7/dist-packages
        enum34: 1.1.6 from /usr/local/lib/python2.7/dist-packages
        ipaddress: 1.0.16 from /usr/local/lib/python2.7/dist-packages
        cffi>=1.4.1: 1.7.0 from /usr/local/lib/python2.7/dist-packages
          pycparser: 2.14 from /usr/local/lib/python2.7/dist-packages
    ndg-httpsclient: 0.4.1 from /usr/local/lib/python2.7/dist-packages
      PyOpenSSL: 16.0.0 from /usr/local/lib/python2.7/dist-packages
        six>=1.5.2: 1.10.0 from /usr/local/lib/python2.7/dist-packages
        cryptography>=1.3: 1.4 from /usr/local/lib/python2.7/dist-packages
          idna>=2.0: 2.1 from /usr/local/lib/python2.7/dist-packages
          pyasn1>=0.1.8: 0.1.9 from /usr/local/lib/python2.7/dist-packages
          six>=1.4.1: 1.10.0 from /usr/local/lib/python2.7/dist-packages
          setuptools>=11.3: 26.1.1 from /usr/local/lib/python2.7/dist-packages
          enum34: 1.1.6 from /usr/local/lib/python2.7/dist-packages
          ipaddress: 1.0.16 from /usr/local/lib/python2.7/dist-packages
          cffi>=1.4.1: 1.7.0 from /usr/local/lib/python2.7/dist-packages
            pycparser: 2.14 from /usr/local/lib/python2.7/dist-packages
    pyasn1: 0.1.9 from /usr/local/lib/python2.7/dist-packages
    six>=1.9.0: 1.10.0 from /usr/local/lib/python2.7/dist-packages
    future: 0.15.2 from /usr/local/lib/python2.7/dist-packages
    protobuf<=3.0.0b2,>=2.6.1: 3.0.0b2 from /usr/local/lib/python2.7/dist-packages
      setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
      six>=1.9: 1.10.0 from /usr/local/lib/python2.7/dist-packages
  requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
  cachetools>=1.0: 1.1.6 from /usr/local/lib/python2.7/dist-packages
Mopidy-Scrobbler: 1.1.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=0.18: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pylast>=0.5.7: 1.6.0 from /usr/local/lib/python2.7/dist-packages
    six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
Mopidy-SoundCloud: 2.0.2 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
Mopidy-Moped: 0.6.4 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.0.0: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
Mopidy-Deezer: 0.1.0 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
  simplejson: 3.8.2 from /usr/local/lib/python2.7/dist-packages
  pycrypto>=2.6.0: 2.6.1 from /usr/local/lib/python2.7/dist-packages
  eyed3>=0.7.9: 0.7.9 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
Mopidy-Podcast: 2.0.1 from /usr/local/lib/python2.7/dist-packages
  uritools>=1.0: 1.0.2 from /usr/local/lib/python2.7/dist-packages
    ipaddress>=1.0.6; python_version == "2.7": 1.0.16 from /usr/local/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  cachetools>=1.0: 1.1.6 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1.1: 2.0.1 from /usr/lib/python2.7/dist-packages
    Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
    requests>=2.0: 2.11.1 from /usr/local/lib/python2.7/dist-packages
    tornado>=2.3: 4.4.1 from /usr/local/lib/python2.7/dist-packages
      singledispatch: 3.4.0.3 from /usr/local/lib/python2.7/dist-packages
        six: 1.10.0 from /usr/local/lib/python2.7/dist-packages
      certifi: 2016.8.31 from /usr/local/lib/python2.7/dist-packages
      backports_abc>=0.4: 0.4 from /usr/local/lib/python2.7/dist-packages
  setuptools: 26.1.1 from /usr/local/lib/python2.7/dist-packages
GStreamer: 1.4.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information:
    Python wrapper: python-gi 3.14.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mpg123audiodec
```

**Comment by belak** [comment] 2016-09-14 23:04
It looks like this is before my rewrite. Essentially, in the old version, a library refresh involves getting the list of songs and querying each of them individually for metadata.

In my rewrite, I use the results from the list and don't make additional calls to the API if they're not needed. There is a prerelease up, or you can install from git, but when the next release happens this should be fixed.

**Comment by jjok** [comment] 2016-09-14 23:32
Should it still be taking a long time to query uploaded songs? I just installed the latest from `develop` and I get.

```
2016-09-14 23:21:44,831 INFO [1029:Thread-8] mopidy_gmusic.backend: Finished refreshing Google Music playlists in 206s
2016-09-14 23:21:53,289 INFO [1029:Thread-7] mopidy_gmusic.backend: Finished refreshing Google Music library in 214s
```

**Comment by belak** [comment] 2016-09-15 08:17
And `mopidy deps` shows you running a 2.x version? If you're running one of the latest versions, I'm fairly stumped.

Ah, alternatively, do you know how many songs are in your library? Even just a rough count would be helpful.

**Comment by jjok** [comment] 2016-09-15 11:08
I've got 8,426 uploaded songs.

**Comment by jjok** [comment] 2016-09-15 11:38
Presumably, that's why it takes a long time. Is it requesting metadata for each track?

Why do you request the library data on startup, rather than just requesting artists, albums, tracks, playlists when a user makes that call in Mopidy?

**Comment by belak** [comment] 2016-09-15 18:46
The library data on startup should be a single API call, and should be fairly fast.

This is the only way to get uploaded tracks via the API, so we cache all library tracks on startup and periodically refresh this.

There is a hard coded cache size (I think it's 1024) which I think you might be running into. I'll look into making that configurable to see if that fixes the problem.

**Comment by jjok** [comment] 2016-09-16 10:46
The number of songs that you can upload for free is 50,000.

What would be the consequence of increasing the limit? More RAM used?

**Comment by belak** [comment] 2016-09-16 11:14
I've had a quick look through the code and it looks like the limit is only for non-library tracks... still trying to determine what might be causing this.

**Comment by jjok** [comment] 2016-09-16 14:07
Is it easier for you if I try debugging it? I haven't really looked into it myself yet.

I don't exactly understand what the refresh is meant to be doing. Could you give me a quick explanation?

**Comment by belak** [comment] 2016-09-16 21:18
That would help. Refresh is simply meant to call `Mobileclient.get_all_songs` which should refresh all songs from the library and store them in a dict locally. This lets most lookups relating to the library use the local cache rather than calling out to the service. Also, this is (as far as I know) the only way to get all uploaded tracks. My library is a bit smaller and doesn't involve as many uploaded tracks, so it's a bit different. It might be worthwhile using `incremental` with `get_all_songs` as an initial step of debugging, so it doesn't wait for grabbing the entire list to finish.

If you'd like pointers, I usually hang out in the #mopidy channel on Freenode as belak... and I'll respond when I can.

**Comment by belak** [comment] 2016-10-31 07:13
I'm changing the milestone for this from 2.0.0 to 2.1.0. I haven't been able to reproduce this and I don't have 8000 tracks to upload to test this. Help would be appreciated and I'd be happy to help debug this. I'm usually available in IRC as belak on freenode (also in the #mopidy channel)

**Comment by jodal** [comment] 2020-12-06 23:35
Closing because Google Play Music has been shut down, and this project is being discontinued.

**Closed by jodal** 2020-12-06 23:35 UTC
Labels: C-bug, good first issue
