### ISSUE TITLE
Gmusic library not being added to Mopidy library

### ISSUE THREAD

**Issue by wilburforce83** [mopidy/mopidy-gmusic#188] opened 2018-03-15 17:31 UTC
Hi, I can browse and play the music with the extension, however, I have to go to browse files > gmusic > subfolders etc.

None of the music being added to the main library, I have checked the view and "all sources" is selected, so it's nothing really silly like that. Is this something it should be doing, or is this expected behaviour?

Many thanks!!

**Comment by grantbaker** [comment] 2018-03-15 23:33
This is exactly how the extension behaves for me as well with no other backend extensions.

However, when I enable Spotify, for example, I can see both my Gmusic playlists and my Spotify playlists under "playlists", but the rest of my Gmusic is still only found in "browse" > "gmusic".

**Comment by wilburforce83** [comment] 2018-03-16 11:09
Yes, it's the same for me. I can see my gmusic playlists under "playlists" - they are automatically added, but the library of music is only available under browse > gmusic. I have read through all the documentation, and I can't seem to find a way to get it in the library, other than it suggests it should just be there automatically.

I have tried to force a library update "sudo mopidyctl local scan"  but it just doesn't see gmusic. Is there perhaps a way we can make it search the location of the gmusic library? I assume there must be a file somewhere with a list of stream links?

**Comment by wilburforce83** [comment] 2018-03-16 12:44
Okay, so I'm not very good with python anyway, and I don't understand the context, so I could be talking nonsense, but it "looks" to me that this section of code inside library.py should be adding the gmusic albums and artists into the album and artists section of mopidy, perhaps something in our config is preventing this from happening correctly?

```
def _to_mopidy_album(self, song):
        name = song.get('album', '')
        artist = self._to_mopidy_album_artist(song)
        date = unicode(song.get('year', 0))

        album_id = song.get('albumId')
        if album_id is None:
            album_id = create_id(artist.name + name + date)

        uri = 'gmusic:album:' + album_id
        images = get_images(song)
        return Album(
            uri=uri,
            name=name,
            artists=[artist],
            num_tracks=song.get('totalTrackCount'),
            num_discs=song.get('totalDiscCount'),
            date=date,
            images=images)

    def _to_mopidy_artist(self, song):
        name = song.get('artist', '')
        artist_id = song.get('artistId')
        if artist_id is not None:
            artist_id = artist_id[0]
        else:
            artist_id = create_id(name)
        uri = 'gmusic:artist:' + artist_id
        return Artist(uri=uri, name=name)

    def _to_mopidy_album_artist(self, song):
        name = song.get('albumArtist', '')
        if name.strip() == '':
            name = song.get('artist', '')
        uri = 'gmusic:artist:' + create_id(name)
        return Artist(uri=uri, name=name)
```

**Comment by kingosticks** [comment] 2018-03-16 13:40
It sounds like you are talking about a very specific user interface here, is this a particular MPD client? Remember that there are many different Mopidy frontends so this report needs a fuller explanation of what you expect to see i.e how does the "main library" differ from browsing? `local scan` is for the Local backend only, that has not effect here.

You'll see that `GMusicLibraryProvider` implements some, but not all, of Mopidy's [LibraryProvider](https://docs.mopidy.com/en/latest/api/backend/#library-provider) interface. It is missing an implementation for `get_distinct()` which the MPD frontend uses to respond to MPD [list](https://docs.mopidy.com/en/latest/modules/mpd/#mopidy.mpd.protocol.music_db.list_) commands. I'm guessing this is what you want. The code you've shown above is only called by `browse`, it's not adding anything to a "main library", Mopidy itself doesn't have any album or artists sections.

**Comment by wilburforce83** [comment] 2018-03-16 13:50
Hi kingosticks!

Thanks! This is a perfect explanation. The issue is the Album and Artists section of all the web interfaces which have in the left menu (Iris in my case).

I assume from what you are saying, this is down to how Iris and others are calling upon the Album and Artist content in their menu i.e. at the moment they are not calling for the Gmusic uri 'gmusic:artist' + 'gmusic:album' ?

is that correct? I wonder if I can add it myself, if that is the case?

Thank you so much for your quick response!

**Comment by kingosticks** [comment] 2018-03-16 14:09
Yes, exactly. Iris is a bit of a weird frontend and I am not sure how it implements that functionality as there's nothing in Mopidy's core interface that explicitly provides it. Furthermore, there's also no convention that backends should provide a browse result for `<some_backend>:artist` and `<some_backend>:album` URIs so although you could do that, it's all a bit fragile. My guess is that parts of Iris are optimised for and tested against specific backends only (i.e. mopidy-spotify). 

I'd start with double checking exactly how Iris tries to populate those Artist and Album sections.

**Comment by jjok** [comment] 2018-03-16 16:21
Which client is @grantbaker using?

**Comment by belak** [comment] 2018-03-16 17:25
I'd be happy to add the missing methods... however, I think part of the confusion when I looked at this initially is based around how gmusic handles the library.

On the web interface, if you add a single song by an artist, when you go to your library it shows up in multiple places - it adds the *entire* artist to the artist tab, it adds the *entire* album to the album tab and it adds the song to the tracks tab.

I suppose the logical thing to do would be to leave `browse` how it is right now and add only the tracks explicitly added to the library for browsing.

**Comment by kingosticks** [comment] 2018-03-16 17:38
The missing method I was talking about is only used by the MPD frontend so it doesn't help here with Iris (a web frontend).

I've had a quick look at Iris. It seems like it bypasses Mopidy completely and grabs that Artist and Album data directly from the Spotify Web API. You would need Iris to add something similar for Gmusic (if it exists).

**Comment by kingosticks** [comment] 2018-03-16 17:41
I tell a lie, it also grabs data for the local backend see [here](https://github.com/jaedb/Iris/blob/b74c6bc3e8fdb5808fb92d9eb3afa552cb17aa74/src/js/services/mopidy/middleware.js#L1743). But as I said before, it's very specific to the local backend and support has to be added in Iris, not here.

**Comment by wilburforce83** [comment] 2018-03-16 17:57
Thank you guys. I really appreciate your help. I think, for the time being I will use the browse function. 

I may try and create a modified Web extension specifically for Google music similar to how iris is for Spotify as it is pretty much my only source of music. No idea how plausible it would be for me to do it but hell,  I'll give it a shot.

**Comment by wilburforce83** [comment] 2018-03-16 18:04
As a side note the Iris search function works well with the gmusic URIs so I may look at how they are doing the search function and see if parts of it can be butchered to be used to add albums and artists to their menu

**Comment by grantbaker** [comment] 2018-03-16 19:35
I was also using Iris, and I just assumed that Iris treated the library the same as any other frontend.

But, as it turns out, I swapped Iris out for other clients like Moped and Material Webclient and the library looked like it behaves as intended.

**Comment by belak** [comment] 2019-04-23 00:42
I'm going to close this for now, as it seems like an issue with iris. Thanks everyone!

**Closed by belak** 2019-04-23 00:42 UTC
