### ISSUE TITLE
Playing sometimes starts in the middle of the track

### ISSUE THREAD

**Issue by 0nse** [mopidy/mopidy-gmusic#114] opened 2016-04-16 15:24 UTC
I have not found any regularity but _sometimes_, when starting to play a track, it will not start from the beginning. Instead, it will start some seconds in. For other songs, it will even start close to the end of the track. This will then happen for all tracks until Mopidy is restarted.

I currently neither have a solution nor further details but think this should at least be noted to see if others face this problem as well.

**Comment by hrkfdn** [comment] 2016-05-04 15:03
Just encountered this as well. Nothing in the server log, though :(

**Comment by belak** [comment] 2016-07-02 22:22
This is an odd issue. I haven't personally run into it, but I'm curious what's causing it.

I'm not sure where it would be on other platforms, but on linux there's also a gmusicapi log which could be useful at `~/.cache/gmusicapi/log/gmusicapi.log`

**Comment by hrkfdn** [comment] 2016-07-02 22:25
I think I found a way to reproduce it:
* Play GMusic track
* Skip forward a little
* Play next track

The next track will start some seconds in.

**Comment by belak** [comment] 2016-07-06 18:55
I believe this is related to mopidy/mopidy#1505

Seeking is fairly broken in mopidy 2.0.0 right now.

**Comment by belak** [comment] 2016-07-14 06:57
I'm going to close this because I was able to reproduce this with mopidy 2.0.0, but not on mopidy's develop branch, so I'm pretty sure this isn't a problem with mopidy-gmusic.

If you continue to have this problem on mopidy's develop branch (or 2.0.1 when that's released) you're welcome to reopen this.

**Closed by belak** 2016-07-14 06:57 UTC
