### ISSUE TITLE
Caching user playlists locally

### ISSUE THREAD

**Issue by BlackLight** [mopidy/mopidy-gmusic#71] opened 2015-01-25 16:52 UTC
By now loading user playlists by looking up all the tracks from GMusic is a very, extremely slow operation. In my case I have something like 20000 tracks in my playlists and this can really take up to 20 minutes for having mopidy+gmusic up & running. Wouldn't it be a good idea to cache trackIDs -> info locally, so we don't have to perform the GMusic lookup every time?

**Comment by jaapz** [comment] 2015-03-17 08:37
+1 this would be great to have

**Comment by berot3** [comment] 2015-03-30 18:13
duplicate of #28

**Comment by jaapz** [comment] 2015-04-09 08:45
@berot3 oh, I forgot I already reported that issue :P

**Comment by jodal** [comment] 2015-09-25 22:03
Closing as duplicate of #28.

**Closed by jodal** 2015-09-25 22:03 UTC
