### ISSUE TITLE
Album tracks out of order?

### ISSUE THREAD

**Issue by geezuh** [mopidy/mopidy-gmusic#203] opened 2018-10-20 14:16 UTC
Using ncmpcpp, when I browse to an album, the tracks are all out of order..

**Comment by benklop** [comment] 2018-11-30 19:57
I can confirm this

**Comment by jodal** [comment] 2020-12-06 23:34
Closing because Google Play Music has been shut down, and this project is being discontinued.

**Closed by jodal** 2020-12-06 23:34 UTC
